-- Source-only reference extracted from SQL_HUNR_2025.sql. No live records.
-- Generated by scripts/Prepare-LegacySource.ps1; MySQL/MariaDB reference, not C++ persistence.
SET NAMES utf8mb4;

CREATE TABLE `array_head_2_frames`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `data` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'JSON array: [id_ct, id_head1, id_head2, ...]',
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `idx_data`(`data`(255) ASC) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `bot_config`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `botname_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL COMMENT 'Danh sách tên bot dạng JSON array, ví dụ: [\"ct1\", \"ct2\", \"ct3\"]',
  `caitrang_id_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL COMMENT 'Danh sách ID cải trang dạng JSON array, ví dụ: [100, 101, 102]',
  `ratio_caitrang` int NULL DEFAULT 30 COMMENT 'Tỉ lệ sử dụng cải trang (0-100)',
  `ratio_trangbi` int NULL DEFAULT 70 COMMENT 'Tỉ lệ sử dụng trang bị (0-100)',
  `is_used` tinyint(1) NOT NULL DEFAULT 0 COMMENT 'Flag đánh dấu config đã được sử dụng (0: chưa dùng, 1: đã dùng)',
  `used_botnames` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL COMMENT 'Danh sách tên bot đã sử dụng dạng JSON array, ví dụ: [\"ct1\", \"ct2\"]',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `comments`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `post_id` int NOT NULL,
  `user_id` int NOT NULL,
  `content` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `post_id`(`post_id` ASC) USING BTREE,
  INDEX `user_id`(`user_id` ASC) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `history_receive_goldbar`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `username` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `player` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `gold_before` int NOT NULL,
  `gold_after` int NOT NULL,
  `number_gold` int NOT NULL,
  `create_date` timestamp NULL DEFAULT current_timestamp,
  `note` varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_achievement`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `content` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `count` int NOT NULL DEFAULT 0,
  `reward` int NOT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_arrow`  (
  `id` int NOT NULL,
  `img` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_background_item`  (
  `id` int NOT NULL,
  `image` int NOT NULL,
  `layer` int NOT NULL,
  `dx` int NOT NULL,
  `dy` int NOT NULL,
  `tile_x` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL,
  `tile_y` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_baisu`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `player1` int NULL DEFAULT NULL,
  `player2` int NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_bo_mong_boss_config`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `do_kho` tinyint NOT NULL COMMENT '0: Easy, 1: Normal, 2: Hard',
  `boss_class_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT 'Tên class của boss',
  `active` tinyint NULL DEFAULT 1,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp,
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `idx_do_kho`(`do_kho` ASC) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = 'Cấu hình boss cho nhiệm vụ Kill Boss' ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_bo_mong_config`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `config_key` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `config_value` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `description` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_key`(`config_key` ASC) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = 'Cấu hình tỷ lệ và tham số hệ thống' ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_bo_mong_history`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `player_id` int NOT NULL,
  `diem_su_dung` int NOT NULL,
  `item_id` int NOT NULL,
  `quantity` int NOT NULL,
  `created_at` bigint NOT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `idx_player_id`(`player_id` ASC) USING BTREE,
  INDEX `idx_created_at`(`created_at` ASC) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = 'Lịch sử nổ hũ của player' ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_bo_mong_moc_diem`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `moc_diem` int NOT NULL COMMENT 'Mốc điểm đạt được',
  `diem_can_thiet` int NOT NULL COMMENT 'Số điểm cần thiết để nổ hũ',
  `item_id_1` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL COMMENT 'JSON reward nhóm 1',
  `item_id_2` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL COMMENT 'JSON reward nhóm 2',
  `item_id_3` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL COMMENT 'JSON reward nhóm 3',
  `item_id_4` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL COMMENT 'JSON reward nhóm 4',
  `active` tinyint(1) NULL DEFAULT 1 COMMENT '1 = bật, 0 = tắt',
  `sort_order` int NULL DEFAULT 0 COMMENT 'Thứ tự hiển thị (số nhỏ trước)',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp,
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `idx_sort_order`(`sort_order` ASC) USING BTREE,
  INDEX `idx_active_sort`(`active` ASC, `sort_order` ASC) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = 'Bộ mộng mốc điểm - reward theo JSON' ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_bo_mong_nhiem_vu`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `player_id` int NOT NULL,
  `loai_nv` tinyint NOT NULL,
  `do_kho` tinyint NOT NULL,
  `yeu_cau` int NOT NULL,
  `tien_do` int NULL DEFAULT 0,
  `diem_thuong` int NOT NULL DEFAULT 0,
  `trang_thai` tinyint NULL DEFAULT 0 COMMENT '0: Đang làm, 1: Hoàn thành',
  `created_at` bigint NOT NULL,
  `expired_at` bigint NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `idx_player_id`(`player_id` ASC) USING BTREE,
  INDEX `idx_trang_thai`(`trang_thai` ASC) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = 'Nhiệm vụ hiện tại của player' ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_bo_mong_nhiem_vu_config`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `loai_nv` tinyint NOT NULL COMMENT '1: Kill Mob, 2: Nạp tiền, 3: Đạt SM, 4: Kill Boss, 5: Nâng trang bị, 6: Train, 7: Làm Task',
  `do_kho` tinyint NOT NULL COMMENT '0: Easy, 1: Normal, 2: Hard',
  `yeu_cau_min` int NOT NULL COMMENT 'Yêu cầu tối thiểu',
  `yeu_cau_max` int NOT NULL COMMENT 'Yêu cầu tối đa',
  `diem_min` int NOT NULL COMMENT 'Điểm thưởng tối thiểu',
  `diem_max` int NOT NULL COMMENT 'Điểm thưởng tối đa',
  `active` tinyint NULL DEFAULT 1 COMMENT '1: Active, 0: Inactive',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp,
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_loai_do_kho`(`loai_nv` ASC, `do_kho` ASC) USING BTREE,
  INDEX `idx_loai_nv`(`loai_nv` ASC) USING BTREE,
  INDEX `idx_do_kho`(`do_kho` ASC) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = 'Cấu hình nhiệm vụ Bò Mộng' ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_caption`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `planet` int NOT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_clan`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `abbreviation` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `leader_id` int NOT NULL,
  `leader_name` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `slogan` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `image_id` int NOT NULL,
  `level` int NOT NULL,
  `clan_point` int NOT NULL,
  `power_point` bigint NOT NULL,
  `max_member` int NOT NULL,
  `item_box` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `create_time` timestamp NOT NULL DEFAULT current_timestamp,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_clan_image`  (
  `id` int NOT NULL,
  `name` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `images` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL,
  `gold` int NOT NULL DEFAULT 0,
  `gem` int NOT NULL DEFAULT 0,
  `is_sale` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_clan_member`  (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `clan_id` int NOT NULL,
  `player_id` int NOT NULL,
  `name` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `role` int NOT NULL,
  `head` int NOT NULL,
  `body` int NOT NULL,
  `leg` int NOT NULL,
  `power_point` bigint NOT NULL,
  `donate` int NOT NULL,
  `receive_donate` int NOT NULL,
  `clan_point` int NOT NULL,
  `current_point` int NOT NULL,
  `clan_reward` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `join_time` timestamp NOT NULL DEFAULT current_timestamp,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_collection_book`  (
  `id` int NOT NULL,
  `name` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `info` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `icon` int NOT NULL,
  `rank` int NOT NULL,
  `max_amount` int NOT NULL,
  `type` int NOT NULL,
  `template_id` int NOT NULL,
  `head` int NOT NULL,
  `body` int NOT NULL,
  `leg` int NOT NULL,
  `bag` int NOT NULL,
  `options` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `aura` int NOT NULL DEFAULT -1,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_consignment_shop`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `seller_id` int NOT NULL,
  `status` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `item_id` int NOT NULL,
  `quantity` int NOT NULL,
  `options` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `price` int NOT NULL,
  `buyer_id` int NOT NULL DEFAULT -1,
  `buy_time` timestamp NULL DEFAULT NULL,
  `receive_time` timestamp NULL DEFAULT NULL,
  `create_time` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_dart`  (
  `id` int NOT NULL,
  `n_update` int NOT NULL,
  `va` int NOT NULL,
  `xd_percent` int NOT NULL,
  `tail` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `tail_border` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `xd1` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `xd2` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `head` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `head_border` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_disciple`  (
  `id` int NOT NULL,
  `name` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `item_body` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `skill` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `info` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `planet` int NOT NULL,
  `status` int NOT NULL,
  `skill_opened` int NOT NULL,
  `type` int NOT NULL,
  `bonus` int NOT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_drop_rate`  (
  `id` int NOT NULL,
  `mob_rate` int NULL DEFAULT 100,
  `boss_rate` int NULL DEFAULT 100,
  `tilephoi_mob` int NULL DEFAULT NULL,
  `tilephoi_boss` int NULL DEFAULT NULL,
  `pet_final_4s` int NULL DEFAULT 2000,
  `pet_final_5s` int NULL DEFAULT 5000,
  `pet_final_6s` int NULL DEFAULT 10000,
  `pet_final_7s` int NULL DEFAULT 30000,
  `pet_final_8s` int NULL DEFAULT 50000,
  `pet_divine` int NULL DEFAULT 50000,
  `pet_destroy` int NULL DEFAULT 50000,
  `dropratefish1` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `dropratefish2` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `dropratefish3` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `dropratefish4` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_effect`  (
  `id` int NOT NULL,
  `info` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_effect_data`  (
  `id` int NOT NULL,
  `image` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL,
  `frame` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL,
  `run` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_event_capsule83`  (
  `id` int UNSIGNED NOT NULL AUTO_INCREMENT,
  `player_name` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `point` int NULL DEFAULT NULL,
  `reward` int NULL DEFAULT 0,
  `create_date` timestamp NULL DEFAULT current_timestamp,
  `modify_date` timestamp NULL DEFAULT current_timestamp,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_event_checkin`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `player_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `checkin_date` datetime NULL DEFAULT NULL,
  `rewarded` tinyint NULL DEFAULT NULL,
  `is_rewarded` int NULL DEFAULT 0,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_event_duongtang`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `player_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `point` int NULL DEFAULT 0,
  `reward` int NULL DEFAULT 0,
  `create_date` datetime NULL DEFAULT NULL,
  `modify_date` datetime NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_event_exchange`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `player_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `point` int NULL DEFAULT 0,
  `reward` int NULL DEFAULT 0,
  `create_date` datetime NULL DEFAULT NULL,
  `modify_date` datetime NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_event_hoahong83`  (
  `id` int UNSIGNED NOT NULL AUTO_INCREMENT,
  `player_name` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `point` int NULL DEFAULT NULL,
  `reward` int NULL DEFAULT 0,
  `create_date` timestamp NULL DEFAULT current_timestamp,
  `modify_date` timestamp NULL DEFAULT current_timestamp,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_event_hopquabac`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `player_name` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `point` int NULL DEFAULT 0,
  `reward` int NULL DEFAULT 0,
  `create_date` timestamp NULL DEFAULT current_timestamp,
  `modify_date` timestamp NULL DEFAULT current_timestamp,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_event_hopquavang`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `player_name` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `point` int NULL DEFAULT 0,
  `reward` int NULL DEFAULT 0,
  `create_date` timestamp NULL DEFAULT current_timestamp,
  `modify_date` timestamp NULL DEFAULT current_timestamp,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_event_khobau`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `player_name` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `point` int NULL DEFAULT 0,
  `reward` int NULL DEFAULT 0,
  `create_date` timestamp NULL DEFAULT current_timestamp,
  `modify_date` timestamp NULL DEFAULT current_timestamp,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_event_noel`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `player_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `point` int NULL DEFAULT 0,
  `create_date` datetime NULL DEFAULT NULL,
  `modify_date` datetime NULL DEFAULT NULL,
  `reward` int NULL DEFAULT 0,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_event_open`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `player_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `point` int NULL DEFAULT 0,
  `reward` int NULL DEFAULT 0,
  `create_date` datetime NULL DEFAULT NULL,
  `modify_date` datetime NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_event_osin_lixi`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `player_id` int NULL DEFAULT NULL,
  `lixi_date` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `idx_player_date`(`player_id` ASC, `lixi_date` ASC) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_event_tet`  (
  `id` int UNSIGNED NOT NULL AUTO_INCREMENT,
  `player_id` int NULL DEFAULT NULL,
  `point` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `create_date` timestamp NULL DEFAULT current_timestamp,
  `modify_date` timestamp NULL DEFAULT current_timestamp,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_event_vqtd`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `player_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `point` int NULL DEFAULT 0,
  `create_date` datetime NULL DEFAULT NULL,
  `modify_date` datetime NULL DEFAULT NULL,
  `reward` int NULL DEFAULT 0,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_game_info`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `title` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `content` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_gift_code`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `server_id` int NOT NULL,
  `code` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `is_activated` int NULL DEFAULT 0,
  `gold` bigint NOT NULL DEFAULT 0,
  `diamond` int NOT NULL DEFAULT 0,
  `diamond_lock` int NOT NULL,
  `items` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `expires_at` timestamp NOT NULL DEFAULT current_timestamp,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp,
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `code_UNIQUE`(`code` ASC) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_gift_code_history`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `player_id` int NULL DEFAULT NULL,
  `gift_code_id` int NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT current_timestamp ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_goldbar_paid_daily`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `user_id` int NOT NULL,
  `user_name` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `current_goldbar_paid` int NOT NULL,
  `goldbar_paid` int NOT NULL,
  `create_date` timestamp NOT NULL DEFAULT current_timestamp,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_history_trade`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `item_bag_1_after` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `item_bag_1_before` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `item_bag_2_after` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `item_bag_2_before` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `item_trade_1` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `item_trade_2` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `player_name_1` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `player_name_2` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `create_time` timestamp NULL DEFAULT current_timestamp,
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `id_UNIQUE`(`id` ASC) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_image`  (
  `id` int NOT NULL,
  `small_image` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_image_by_name`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `filename` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `n_frame` int NOT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_infoclient`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `player_id` int NULL DEFAULT NULL,
  `infoClient` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT current_timestamp ON UPDATE CURRENT_TIMESTAMP,
  `isConfirm` tinyint NULL DEFAULT NULL,
  `lastConfirm` bigint NULL DEFAULT NULL,
  `player_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `ipLogin` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `countPing` int NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_isvaliddll`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `nameDll` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_item`  (
  `id` int NOT NULL,
  `name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `type` int NOT NULL,
  `gender` int NOT NULL,
  `description` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `level` int NOT NULL,
  `require` int NOT NULL,
  `resale_price` int NOT NULL DEFAULT -1,
  `icon` int NOT NULL,
  `part` int NOT NULL,
  `is_up_to_up` int NOT NULL,
  `head` int NOT NULL DEFAULT -1,
  `body` int NOT NULL DEFAULT -1,
  `leg` int NOT NULL DEFAULT -1,
  `options` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL,
  `mount_id` int NOT NULL DEFAULT -1,
  `lock` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_item_option_template`  (
  `id` int NOT NULL,
  `type` int NOT NULL,
  `name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_items_cms`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `pId` int NOT NULL,
  `itemid` int NOT NULL,
  `quantity` int NOT NULL,
  `status` tinyint(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_lucky_wheel`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `type` int NOT NULL,
  `item_id` int NOT NULL,
  `quantity` int NOT NULL,
  `rate` double NOT NULL,
  `expire` int NOT NULL DEFAULT -1,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_mabu_egg`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `player_id` int NULL DEFAULT NULL,
  `last_time_create` bigint NULL DEFAULT NULL,
  `time_done` bigint NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `idx_player_id`(`player_id` ASC) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_map`  (
  `id` int NOT NULL,
  `name` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `planet` int NOT NULL DEFAULT 0,
  `tile_id` int NOT NULL DEFAULT 0,
  `bg_id` int NOT NULL DEFAULT 0,
  `type` int NOT NULL DEFAULT 0,
  `waypoint` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL,
  `mob` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL,
  `npc` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL,
  `position_bg_item` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL,
  `effect` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL,
  `effect_event` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL,
  `bg_type` int NOT NULL DEFAULT 0,
  `zone_number` int NOT NULL DEFAULT 15,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_mob_template`  (
  `id` int NOT NULL,
  `name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `level` int NOT NULL DEFAULT 1,
  `type` int NOT NULL,
  `new` int NOT NULL,
  `hp` int NOT NULL,
  `range_move` int NOT NULL,
  `speed` int NOT NULL,
  `dart_type` int NOT NULL,
  `image` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL,
  `frame` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL,
  `run` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL,
  `frame_boss` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_npc_template`  (
  `id` int NOT NULL,
  `name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `head` int NOT NULL,
  `body` int NOT NULL,
  `leg` int NOT NULL,
  `menu` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_others`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `key` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `value` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_part`  (
  `id` int NOT NULL,
  `type` int NOT NULL,
  `part` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `note` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_player`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `user_id` int NOT NULL,
  `server_id` bigint UNSIGNED NOT NULL,
  `name` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `gender` int NOT NULL,
  `class_id` int NOT NULL,
  `head` int NOT NULL,
  `task` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL,
  `gold` bigint NOT NULL DEFAULT 0,
  `gem` int NOT NULL DEFAULT 0,
  `gem_lock` int NOT NULL DEFAULT 0,
  `item_bag` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `item_body` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `item_box` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `box_crack_ball` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `map` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `skill` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `info` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `clan` int NOT NULL DEFAULT -1,
  `shortcut` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `magic_tree` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `number_cell_bag` int NOT NULL DEFAULT 20,
  `number_cell_box` int NOT NULL DEFAULT 20,
  `friend` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `enemy` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `ship` int NOT NULL DEFAULT 0,
  `fusion` int NOT NULL DEFAULT 1,
  `porata` int NOT NULL DEFAULT 0,
  `item_time` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `amulet` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `achievement` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `studying` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `time_played` int NOT NULL DEFAULT 0,
  `type_trainning` tinyint NOT NULL DEFAULT 0,
  `online` tinyint NOT NULL DEFAULT 0,
  `time_at_split_fusion` bigint NOT NULL DEFAULT 0,
  `head2` int NOT NULL DEFAULT -1,
  `body` int NOT NULL DEFAULT -1,
  `leg` int NOT NULL DEFAULT -1,
  `collection_book` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `count_number_of_specialskill_changes` int NOT NULL DEFAULT 0,
  `special_skill` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `total_gold_bar` int NULL DEFAULT 0,
  `reset_time` timestamp NOT NULL DEFAULT current_timestamp,
  `login_time` timestamp NULL DEFAULT NULL,
  `logout_time` timestamp NULL DEFAULT NULL,
  `create_time` timestamp NOT NULL DEFAULT current_timestamp,
  `base_name` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `dataDHVT23` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `thoivang` int NOT NULL DEFAULT 0,
  `drop_item` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `point_bo_mong` int NULL DEFAULT 0 COMMENT 'Điểm tích lũy Bò Mộng',
  `count_nhiem_vu_bo_mong` int NULL DEFAULT 0 COMMENT 'Số nhiệm vụ đã làm hôm nay',
  `last_reset_nv_bo_mong` bigint NULL DEFAULT 0 COMMENT 'Thời gian reset NV',
  `last_coin_value` int NULL DEFAULT 0 COMMENT 'Coin cũ để check nạp tiền',
  `count_task_completed_today` int NULL DEFAULT 0 COMMENT 'Số task đã hoàn thành hôm nay',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `idx_nr_player_user_id`(`user_id` ASC) USING BTREE,
  INDEX `idx_point_bo_mong`(`point_bo_mong` ASC) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_power`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `power` bigint NOT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_rewardtop`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `player_name` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `item` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `isReward` tinyint NOT NULL,
  `infoTop` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_salon`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `item_id` int NOT NULL,
  `buy_gold` int NOT NULL,
  `buy_gem` int NOT NULL,
  `options` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `expired` int NOT NULL DEFAULT -1,
  `new` int NOT NULL,
  `preview` int NOT NULL,
  `tab` int NOT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_security`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `versionPC` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `modPC` bigint NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_shop_amulet`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `item_id` int NOT NULL,
  `buy_gold` int NOT NULL,
  `buy_gem` int NOT NULL,
  `options` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `expired` int NOT NULL DEFAULT -1,
  `new` int NOT NULL,
  `preview` int NOT NULL,
  `tab` int NOT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_shop_bulma`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `item_id` int NOT NULL,
  `buy_gold` int NOT NULL,
  `buy_gem` int NOT NULL,
  `options` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `expired` int NOT NULL DEFAULT -1,
  `new` int NOT NULL,
  `preview` int NOT NULL,
  `tab` int NOT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_shop_bunma_tet`  (
  `id` int NOT NULL,
  `item_id` int NOT NULL,
  `icon_special` int NOT NULL,
  `buy_special` int NOT NULL,
  `options` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `expired` int NOT NULL DEFAULT -1,
  `new` int NOT NULL,
  `preview` int NOT NULL,
  `tab` int NOT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_shop_clan`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `item_id` int NOT NULL,
  `icon_special` int NOT NULL,
  `buy_special` int NOT NULL,
  `options` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `expired` int NOT NULL DEFAULT -1,
  `new` int NOT NULL,
  `preview` int NOT NULL,
  `tab` int NOT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `item_id`(`item_id` ASC) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_shop_equipment`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `item_id` int NOT NULL,
  `buy_gold` int NOT NULL,
  `buy_gem` int NOT NULL,
  `options` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `new` int NOT NULL,
  `expired` int NOT NULL DEFAULT -1,
  `preview` int NOT NULL,
  `tab` int NOT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_shop_food_kemdau`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `item_id` int NOT NULL,
  `icon_special` int NOT NULL,
  `buy_special` int NOT NULL,
  `options` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `expired` int NOT NULL DEFAULT -1,
  `new` int NOT NULL,
  `preview` int NOT NULL,
  `tab` int NOT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `item_id`(`item_id` ASC) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_shop_food_mily`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `item_id` int NOT NULL,
  `icon_special` int NOT NULL,
  `buy_special` int NOT NULL,
  `options` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `expired` int NOT NULL DEFAULT -1,
  `new` int NOT NULL,
  `preview` int NOT NULL,
  `tab` int NOT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `item_id`(`item_id` ASC) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_shop_food_pudding`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `item_id` int NOT NULL,
  `icon_special` int NOT NULL,
  `buy_special` int NOT NULL,
  `options` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `expired` int NOT NULL DEFAULT -1,
  `new` int NOT NULL,
  `preview` int NOT NULL,
  `tab` int NOT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `item_id`(`item_id` ASC) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_shop_food_sushi`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `item_id` int NOT NULL,
  `icon_special` int NOT NULL,
  `buy_special` int NOT NULL,
  `options` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `expired` int NOT NULL DEFAULT -1,
  `new` int NOT NULL,
  `preview` int NOT NULL,
  `tab` int NOT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `item_id`(`item_id` ASC) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_shop_food_xucxich`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `item_id` int NOT NULL,
  `icon_special` int NOT NULL,
  `buy_special` int NOT NULL,
  `options` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `expired` int NOT NULL DEFAULT -1,
  `new` int NOT NULL,
  `preview` int NOT NULL,
  `tab` int NOT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `item_id`(`item_id` ASC) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_shop_huy_diet`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `item_id` int NOT NULL,
  `new` tinyint NULL DEFAULT 0,
  `icon_special` int NOT NULL,
  `buy_special` int NOT NULL,
  `options` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `expired` int NOT NULL DEFAULT -1,
  `tab` int NOT NULL,
  `preview` int NULL DEFAULT 0,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_shop_itemdetu`  (
  `id` int NOT NULL,
  `item_id` int NOT NULL,
  `icon_special` int NOT NULL,
  `buy_special` int NOT NULL,
  `options` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `expired` int NOT NULL DEFAULT -1,
  `new` int NOT NULL,
  `preview` int NOT NULL,
  `tab` int NOT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_shop_linhthu`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `item_id` int NOT NULL,
  `icon_special` int NOT NULL,
  `buy_special` int NOT NULL,
  `options` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `expired` int NOT NULL DEFAULT -1,
  `new` tinyint(1) NOT NULL DEFAULT 0,
  `preview` tinyint(1) NOT NULL DEFAULT 0,
  `tab` int NOT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_shop_ltn`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `item_id` int NULL DEFAULT NULL,
  `buy_gold` int NULL DEFAULT NULL,
  `buy_gem` int NULL DEFAULT NULL,
  `new` int NULL DEFAULT NULL,
  `options` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `preview` int NULL DEFAULT NULL,
  `tab` int NULL DEFAULT NULL,
  `expired` int NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_shop_lytieunuong`  (
  `id` int NOT NULL,
  `item_id` int NOT NULL,
  `icon_special` int NOT NULL,
  `buy_special` int NOT NULL,
  `options` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `expired` int NOT NULL DEFAULT -1,
  `new` int NOT NULL,
  `preview` int NOT NULL,
  `tab` int NOT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_shop_popo`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `item_id` int NOT NULL,
  `icon_special` int NOT NULL,
  `buy_special` int NOT NULL,
  `options` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `expired` int NOT NULL DEFAULT -1,
  `new` tinyint(1) NOT NULL DEFAULT 0,
  `preview` tinyint(1) NOT NULL DEFAULT 0,
  `tab` int NOT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_shop_santa`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `item_id` int NOT NULL,
  `buy_gold` int NOT NULL,
  `buy_gem` int NOT NULL,
  `options` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `expired` int NOT NULL DEFAULT -1,
  `new` int NOT NULL,
  `preview` int NOT NULL,
  `tab` int NOT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_shop_thientu`  (
  `id` int NOT NULL,
  `item_id` int NOT NULL,
  `icon_special` int NOT NULL,
  `buy_special` int NOT NULL,
  `options` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `expired` int NOT NULL DEFAULT -1,
  `new` int NOT NULL,
  `preview` int NOT NULL,
  `tab` int NOT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_shop_tv`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `item_id` int NOT NULL,
  `icon_special` int NOT NULL,
  `buy_special` int NOT NULL,
  `options` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `expired` int NOT NULL DEFAULT -1,
  `new` int NOT NULL,
  `preview` int NOT NULL,
  `tab` int NOT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `item_id`(`item_id` ASC) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_shop_uron`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `item_id` int NOT NULL,
  `buy_gold` int NOT NULL,
  `buy_gem` int NOT NULL,
  `options` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `expired` int NOT NULL DEFAULT -1,
  `new` int NOT NULL,
  `preview` int NOT NULL,
  `tab` int NOT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_shop_whis`  (
  `id` int NOT NULL,
  `item_id` int NOT NULL,
  `icon_special` int NOT NULL,
  `buy_special` int NOT NULL,
  `options` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `expired` int NOT NULL DEFAULT -1,
  `new` int NOT NULL,
  `preview` int NOT NULL,
  `tab` int NOT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_skill`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `skill_id` int NOT NULL,
  `class` int NOT NULL,
  `name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `description` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `max_point` int NOT NULL,
  `mana_use_type` int NOT NULL,
  `type` int NOT NULL,
  `icon` int NOT NULL,
  `info` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `skills` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_skill_disciple`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `power_require` bigint NOT NULL,
  `skills` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_skill_option_template`  (
  `id` int NOT NULL,
  `name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_skill_paint`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `skill_id` int NOT NULL,
  `on_mob` int NOT NULL,
  `num_eff` int NOT NULL,
  `skill_stand` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `skill_fly` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_special_skill`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `info` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `icon` int NOT NULL,
  `min` int NOT NULL,
  `max` int NOT NULL,
  `planet` int NOT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_statistic`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `ccu` int NULL DEFAULT 0,
  `create_date` datetime NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_statistic_server`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `player_id` int NULL DEFAULT NULL,
  `player_name` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `gold_bar` int NULL DEFAULT 0,
  `gold_bar_spent_today` int NULL DEFAULT 0,
  `ao_than_linh` int NULL DEFAULT 0,
  `quan_than_linh` int NULL DEFAULT 0,
  `gang_than_linh` int NULL DEFAULT 0,
  `giay_than_linh` int NULL DEFAULT 0,
  `nhan_than_linh` int NULL DEFAULT 0,
  `item_cap2` int NULL DEFAULT 0,
  `nr_1s` int NULL DEFAULT 0,
  `nr_2s` int NULL DEFAULT 0,
  `nr_3s` int NULL DEFAULT 0,
  `has_set_thien_menh` tinyint(1) NULL DEFAULT 0,
  `create_date` datetime NULL DEFAULT current_timestamp,
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_player_id`(`player_id` ASC) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_super_rank`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `player_id` int NOT NULL,
  `rank` int NOT NULL,
  `info` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `data` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
  `event_newyear2026` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `player_id`(`player_id` ASC) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_task`  (
  `id` int NOT NULL,
  `name` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `details` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `subnames` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `counts` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `npcs` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `maps` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `contents` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `reward_power` bigint NOT NULL DEFAULT 0,
  `reward_potential` int NOT NULL DEFAULT 0,
  `reward_gold` int NOT NULL DEFAULT 0,
  `reward_gem` int NOT NULL DEFAULT 0,
  `reward_gem_lock` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_top_boss`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `player_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `point` int NULL DEFAULT 0,
  `reward` int NULL DEFAULT 0,
  `create_date` datetime NULL DEFAULT NULL,
  `modify_date` datetime NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_top_dhvt_sieu_hang_1`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `player_id` int NOT NULL,
  `top` int NOT NULL,
  `is_reward` int NOT NULL,
  `create_date` timestamp NOT NULL DEFAULT current_timestamp,
  `modify_date` timestamp NOT NULL DEFAULT current_timestamp,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_top_nap`  (
  `id` int UNSIGNED NOT NULL AUTO_INCREMENT,
  `player_name` int NULL DEFAULT NULL,
  `point` int NULL DEFAULT NULL,
  `reward` int NULL DEFAULT 0,
  `create_date` datetime NULL DEFAULT current_timestamp,
  `modify_date` datetime NULL DEFAULT current_timestamp,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_top_nrsd`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `player_name` int NULL DEFAULT NULL,
  `point` int NULL DEFAULT 0,
  `reward` int NULL DEFAULT 0,
  `create_date` datetime NULL DEFAULT current_timestamp,
  `modify_date` datetime NULL DEFAULT current_timestamp,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_top_power`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `player_name` int NULL DEFAULT NULL,
  `point` int NULL DEFAULT 0,
  `reward` int NULL DEFAULT 0,
  `create_date` datetime NULL DEFAULT current_timestamp,
  `modify_date` datetime NULL DEFAULT current_timestamp,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_top_superrank`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `player_id` int NOT NULL,
  `rank` int NULL DEFAULT 0,
  `create_time` bigint NULL DEFAULT 0,
  `reward` tinyint NULL DEFAULT 0,
  `create_date` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_user`  (
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `password` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `status` tinyint NOT NULL DEFAULT 0,
  `gold_bar` int NULL DEFAULT 0,
  `coin` int NULL DEFAULT 0,
  `lock_gold` timestamp NULL DEFAULT NULL,
  `lock_time` timestamp NULL DEFAULT NULL,
  `activated` int NOT NULL DEFAULT 0,
  `role` int NOT NULL DEFAULT 0 COMMENT '0: user, 1: admin',
  `create_time` timestamp NOT NULL DEFAULT current_timestamp,
  `ip` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT 'none',
  `domain` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT 'none',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `users_username_unique`(`username` ASC) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_whis`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `player_id` int NOT NULL,
  `current_level` int NOT NULL,
  `create_date` date NOT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `nr_whis_reward`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `player_id` int NOT NULL,
  `point` int NOT NULL,
  `reward` int NOT NULL,
  `create_date` timestamp NOT NULL DEFAULT current_timestamp,
  `modify_date` timestamp NOT NULL DEFAULT current_timestamp,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `posts`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `title` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `content` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `category` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT 'Thông Báo',
  `author_id` int NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `author_id`(`author_id` ASC) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;
