package com.ngocrong.combine;

public enum CombineType {
    CHUYEN_HOA,
    EP_PHA_LE,
    NANG_CAP,
    NANG_OPTION_PORATA,
    NANG_OPTION_PORATA_CAP_3,
    NANG_PORATA,
    NANG_PORATA_CAP_3,
    NHAP_DA,
    NHAP_NGOC,
    PHA_LE_HOA,
    HUY_DIET,
    KICH_HOAT,
    GHEP_DA,
    TACH_DO,
    TACH_DO_KICH_HOAT,
    NANG_CAP_2,
    Tach_Vat_Pham,
    Nang_Item_De_Tu,
    CAPSULE_VIPPRO,
    CAPSULE_VIPPRO_OPTION,
    AP_LINH_THU,
    NANG_CAP_LINH_THU,
    NANG_BAC_LINH_THU,
    NANG_CHI_SO_LINH_THU,
    XOA_CHI_SO_LINH_THU,
    NANG_CAP_CHAN_THIEN_TU
}
